### PR TITLE
Handle missing tree age when creating CSVs

### PR DESCRIPTION
**Pull request by JensWinter**
Trees without a planted date (i.e. age) won't be uploaded to mapbox properly.
The CSV files which get generated during a harvest run don't have an age cell for these cases. I guess this leads to them not being imported by the Mapbox Uploads API.

This PR makes sure that there is an empty cell in case a tree doesn't have age data.

### CODE REVIEW

**Comment by ff6347** [comment]
Hi @JensWinter LGTM. I noticed that our tests are totally outdated and still use the old database setup. I'll will have to fix this. Are you in a hurry with that? Or are you using your fork and the PR is just a gift? :)

**Comment by ff6347** [comment]
Hi  @JensWinter I Update the workflow on staging. I think I had a miss configured env variable for the bucket. Can you update your branch to have these changes? So we can see if the tests pass.

**Comment by JensWinter** [comment]
Hey @ff6347, done. Should be ready to run the tests now.

**Comment by ff6347** [comment]
Seems to be some mixup with env variables. I'll review them after the holiday.

**Comment by ff6347** [comment]
Ahhhhhh. The test fails because you are working on a fork. I'll add you as a contributor.

> Anyone with collaborator access to this repository can use these secrets and variables for actions. They are not passed to workflows that are triggered by a pull request from a fork.

**Comment by ff6347** [comment]
@all-contributors please add @JensWinter for code and bugs

**Pull request merged**
