### PR TITLE
feat: generate tree click cylinders

### PR DESCRIPTION
**Pull request by Jaszkowic**
this is needed for 3d trees: https://github.com/technologiestiftung/giessdenkiez-de/pull/667

### CODE REVIEW

**Review by ff6347 — COMMENTED** [review]
I'm not gonna dive into the depth of the code, because I guess you tested that the generated tileset works.

One question:

- the tileset for the trees will contain only the trees or also the rain water information from the DWD? If not why generate it every day?
- I get the feeling that the DWD harvester is becoming a "Eierlegendewollmilchsau" should it really do the generation of the tilesets for the 3d trees as well?

**Comment by Jaszkowic** [comment]
@ff6347 

> I get the feeling that the DWD harvester is becoming a "Eierlegendewollmilchsau" should it really do the generation of the tilesets for the 3d trees as well?

Definitely not. Putting it into DWD harvester was just the quickest way. It's definitely dirty. I suggest the following:

- Keep all weather-related DWD stuff in this repository
- Move the generation of tilesets into a new repository, maybe called `giessdenkiez-tileset-generator` (right now, this would handle the creation / updating of the normal trees tilesets and the tree cylinders)

As the DWD harvester also updates trees in the database (with the fetched weather information), we then need to make sure that DWD runs first and the Tileset generation afterwards. It will create a little bit of work setting up new Github Actions etc. , but I would also like to have a cleaner / new project for tileset generation.

> the tileset for the trees will contain only the trees or also the rain water information from the DWD? If not why generate it every day?

The tilesets contain the `radolan_sum`, which contains the updated water information from DWD, that's why we update it daily

**Comment by ff6347** [comment]
> @ff6347
> 
> > I get the feeling that the DWD harvester is becoming a "Eierlegendewollmilchsau" should it really do the generation of the tilesets for the 3d trees as well?
> 
> Definitely not. Putting it into DWD harvester was just the quickest way. It's definitely dirty. I suggest the following:
> 
>     * Keep all weather-related DWD stuff in this repository
> 
>     * Move the generation of tilesets into a new repository, maybe called `giessdenkiez-tileset-generator` (right now, this would handle the creation / updating of the normal trees tilesets and the tree cylinders)
> 

Yes. That sounds good.

> 
> As the DWD harvester also updates trees in the database (with the fetched weather information), we then need to make sure that DWD runs first and the Tileset generation afterwards. It will create a little bit of work setting up new Github Actions etc. , but I would also like to have a cleaner / new project for tileset generation.
> 

We can use repository dispatch actions (I think). Its like webhooks.

> > the tileset for the trees will contain only the trees or also the rain water information from the DWD? If not why generate it every day?
> 
> The tilesets contain the `radolan_sum`, which contains the updated water information from DWD, that's why we update it daily

The tileset for the trees dots. Yes but do the 3D trees need the radolan sum?

**Comment by Jaszkowic** [comment]
> The tileset for the trees dots. Yes but do the 3D trees need the radolan sum?

No, the cylinder tilesets for the 3D trees do not need the radolan sum. They can be generated once (or whenever we add / remove trees or change tree positions)

**Comment by ff6347** [comment]
> > The tileset for the trees dots. Yes but do the 3D trees need the radolan sum?
> 
> No, the cylinder tilesets for the 3D trees do not need the radolan sum. They can be generated once (or whenever we add / remove trees or change tree positions)

That would be good. Since every tile set generation costs money

**Review by ff6347 — APPROVED** [review]
I guess for the first draft and verification, proof, go this way and merge to have your tile sets. Then we make a plan how the new harvester could be structured

**Pull request merged**
